version: '3.8'
services:
  app:
    image: dailytasks
    ports:
      - "8080:8080"
    depends_on:
      - db
      - jaeger
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://localhost:1434;databaseName=Labor;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Hochschule123!

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Hochschule123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"  # For UDP-based instrumentations
      - "16686:16686"    # Jaeger UI
      - "14250:14250"    # gRPC collector port
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411